### ISSUE TITLE
cm10.1のbluetoothが弱い

### ISSUE THREAD

**Issue by Matix8** [kbc-developers/android_device_samsung_d2dcm#1]
一応繋がれますが、電波が弱いです。特にbtで音楽を聞いてみたら、気がつきます。低音もあまり聞こえません。携帯の下部分(ボタンのところ)を持てば、btの電波が飛べなくなちゃって、音が消えます。

**Comment by sakuramilk** [comment]
cwmからinstallしてください
https://dl.dropbox.com/u/63613486/SC-06D/tmp/wifi-test-d2dcm.zip

これで改善されなければ現状対応不可能なので割り切ってください。

**Comment by Matix8** [comment]
installしました。使い方を教えていただけませんか？ 新しいアプリが表示しなくて、 install出来たのかな。

**Comment by ma34s** [comment]
・・・　中見たらアプリじゃないですね
system内のバイナリ(wifiのfirmware)です。
使い方ではなくinstallした状態で動作確認して改善するかどうかですね。

入れた上で、変わらないのであれば、「対応不可能」という事かと

**Comment by Matix8** [comment]
なるほど、説明ありがとうございます。これ入れて、大分良くなりました。電波妨害と低音問題も良くなったみたいです。明日、また試し続けます。

**Comment by Matix8** [comment]
このバイナリを入れると、 最初はbluetooth治ったが、しばらく使えば電波が悪くなります。さらに、バイナリ installした後、 Wi-Fiの接続はうまく繋がらないです。私としてはもっとの問題は bluetoothだけでしたので、 Wi-Fiは元のままでよかったと思います。 bluetoothはおしい感じですね。

**Comment by sakuramilk** [comment]
firmwareの原因、dcm用jbが出れば改善される可能性あり
