### ISSUE TITLE
No sound with video recording

### ISSUE THREAD

**Issue by remidesroques** [kbc-developers/android_device_samsung_d2dcm#4]
Hello @sakuramilk @HomuHomu ,

Problem: There is no sound when we record a video (problem reported by many users)

TEST: 
Maybe I thought it is a rom problem 
-> we tried Pacman, carbon and your CM10 remix all on kernel 3.4.50 by homura (SC06D-JB-MR1-KBC-20130625-AOSP)
-> all no sound

RESULT:
So maybe it's a kernel problem

**Comment by jeremyssf** [comment]
Twitterのポストを翻訳：
Translation from two twitter posts by Homura:
I know snd_soc_msm has been changed on the CyanogenMod side but there is a fill or merge required between this source code and official SC06D_JB source code. It needs to be fixed but how exactly, I'm not sure.

As for CM, until the Android 4.3 release I will either wait or try to consider what I can do. At any rate, the sound issue stems from the difference between the USA device and Japanese device. Currently, a quick fix doesn't seem easy.
